/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/projetos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Projetos
         * @description Lista os projetos do studio.
         */
        get: operations["listar_projetos_projetos_get"];
        put?: never;
        /**
         * Criar Projeto
         * @description Registra um projeto novo com seu contexto e a dor do usuário.
         */
        post: operations["criar_projeto_projetos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hipoteses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Hipoteses
         * @description Lista as hipóteses de valor registradas, com seu estado atual.
         */
        get: operations["listar_hipoteses_hipoteses_get"];
        put?: never;
        /**
         * Criar Hipotese
         * @description Registra uma hipótese de valor no formato Se / então / porque.
         */
        post: operations["criar_hipotese_hipoteses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HipoteseIn */
        HipoteseIn: {
            /** Projeto Id */
            projeto_id: number;
            /**
             * Se
             * @example o Copilot sugerir enquadramentos baseados em MVPs anteriores
             */
            se: string;
            /**
             * Entao
             * @example Marina reduz o tempo entre a ideia e o enquadramento pronto
             */
            entao: string;
            /**
             * Porque
             * @example ela deixa de partir do zero e passa a revisar em vez de criar
             */
            porque: string;
            /**
             * Metrica
             * @example dias entre a entrada da ideia e o enquadramento pronto
             */
            metrica: string;
            /**
             * Baseline
             * @example 20 dias
             */
            baseline: string;
            /**
             * Alvo
             * @example 10 dias
             */
            alvo: string;
            /**
             * Estado
             * @default em_teste
             * @enum {string}
             */
            estado: "em_teste" | "confirmada" | "inconclusiva" | "refutada";
        };
        /** HipoteseOut */
        HipoteseOut: {
            /** Projeto Id */
            projeto_id: number;
            /**
             * Se
             * @example o Copilot sugerir enquadramentos baseados em MVPs anteriores
             */
            se: string;
            /**
             * Entao
             * @example Marina reduz o tempo entre a ideia e o enquadramento pronto
             */
            entao: string;
            /**
             * Porque
             * @example ela deixa de partir do zero e passa a revisar em vez de criar
             */
            porque: string;
            /**
             * Metrica
             * @example dias entre a entrada da ideia e o enquadramento pronto
             */
            metrica: string;
            /**
             * Baseline
             * @example 20 dias
             */
            baseline: string;
            /**
             * Alvo
             * @example 10 dias
             */
            alvo: string;
            /**
             * Estado
             * @default em_teste
             * @enum {string}
             */
            estado: "em_teste" | "confirmada" | "inconclusiva" | "refutada";
            /** Id */
            id: number;
            /**
             * Criado Em
             * Format: date-time
             */
            criado_em: string;
        };
        /** ProjetoIn */
        ProjetoIn: {
            /**
             * Nome
             * @example Paris Group Copilot
             */
            nome: string;
            /**
             * Contexto
             * @example Um cliente procurou o studio com um pedido específico.
             */
            contexto: string;
            /**
             * Dor Usuario
             * @example Marina leva 20 dias entre a ideia e o enquadramento pronto.
             */
            dor_usuario: string;
        };
        /** ProjetoOut */
        ProjetoOut: {
            /**
             * Nome
             * @example Paris Group Copilot
             */
            nome: string;
            /**
             * Contexto
             * @example Um cliente procurou o studio com um pedido específico.
             */
            contexto: string;
            /**
             * Dor Usuario
             * @example Marina leva 20 dias entre a ideia e o enquadramento pronto.
             */
            dor_usuario: string;
            /** Id */
            id: number;
            /**
             * Criado Em
             * Format: date-time
             */
            criado_em: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listar_projetos_projetos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjetoOut"][];
                };
            };
        };
    };
    criar_projeto_projetos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjetoIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjetoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_hipoteses_hipoteses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HipoteseOut"][];
                };
            };
        };
    };
    criar_hipotese_hipoteses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HipoteseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HipoteseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
